# Math
In this notebook we will study some math module.

## Random
Python provides a module to support some random numbers.

| Function Name | Explanation |
| --- | --- |
| randint(x, y) | generate a random int in [x, y] |
| random() | generate a random float from [0, 1) |
| uniform(x, y) | generate a random float from [x, y) |
| choice([]) |   return a random element in the array |
| shuffle([]) | suffle an array |
| sample([], int) | return a few random elements in array |
| seed(x) | start to a specific list of random number | 


In [15]:
# Generate a list of integer
import random

# generate 10 random integer
print("random 1 - 10", list(random.randint(1, 10) for n in range(1, 11)))


# select random elements in the array
fruits = ['apple', 'banana', 'watermelon', 'peach', 'orange']
print("fruits = ", fruits)
print("random fruits = ", list(random.choice(fruits) for n in range(1, 6)))

# shuffle pokers
pokers = ['2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K', 'A']
print("Before shuffle :", pokers) 
for i in range(1, 11) :
    random.shuffle(pokers)
print ("After shuffle :", pokers)

# select multiple random numbers
lottery = random.sample(range(1, 50), 7)
special = lottery.pop()
lottery.sort()
print("lottery = ", lottery, ", special number = ", special)

# generate random float numbers
print("random float numbers = ", list(round(random.uniform(10, 20), 3) for n in range(1, 11)))


random 1 - 10 [9, 1, 3, 9, 1, 9, 9, 2, 6, 8]
fruits =  ['apple', 'banana', 'watermelon', 'peach', 'orange']
random fruits =  ['watermelon', 'peach', 'watermelon', 'orange', 'watermelon']
Before shuffle : ['2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K', 'A']
After shuffle : ['9', '2', '8', 'J', '7', '10', 'Q', '3', '6', 'A', 'K', '5', '4']
lottery =  [11, 13, 33, 36, 37, 45] , special number =  12
random float numbers =  [10.262, 15.51, 13.177, 10.571, 17.037, 14.143, 13.773, 16.338, 14.507, 19.48]


## Decimal
We can calculate float in accurate decimal. This is normally used in commercial scenarios.

In [1]:
# decimal for precise calculation
from decimal import Decimal
a = 4.2
b = 2.1
print("a = ", a, ", b = ", b, ", a+b=", a+b)
a = Decimal('4.2')
b = Decimal('2.1')
print("a = ", a, ", b = ", b, ", a+b=", a+b)
print("a/b = ", round(a/b, 3))

a =  4.2 , b =  2.1 , a+b= 6.300000000000001
a =  4.2 , b =  2.1 , a+b= 6.3
a/b =  2.000


#### fsum

In [2]:
import math
nums = [1.23E+18, 1, -1.23E18]
print("nums = ", nums)
print("sum(nums)", sum(nums))
math.fsum(nums)
print("math.fsum(nums)", math.fsum(nums))


nums =  [1.23e+18, 1, -1.23e+18]
sum(nums) 0.0
math.fsum(nums) 1.0


### Fractions

In [9]:
from fractions import Fraction
a = Fraction(5, 4)
b = Fraction(7, 16)
print("a = ", a, "; b = ", b, "; a + b = ", a + b)
print("a * b = ", a * b)
c = Fraction(4, 6)
print("c.numerator = ", c.numerator)
print("c.denominator = ", c.denominator)


a =  5/4 ; b =  7/16 ; a + b =  27/16
a * b =  35/64
c.numerator =  2
c.denominator =  3


## Numpy arrays
Numpy arrays are used to calculate array and liner algebra

#### Matrix calculation

In [21]:
# calculate matrix
import numpy as np
ax = np.array([1,2,3,4])
ay = np.array([5,6,7,8])
print("ax = ", ax, "; ay = ", ay)
print("ax + ay = ", ax + ay)
print("ax * ay = ", ax * ay)
print("np.sqrt(ax) = ", np.sqrt(ax))

# select rows and columns
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
# select row 1 
print("a[1]", a[1])
# select col 1 
print("a[:,1]", a[:,1])
c = np.where(a < 10, a, 10)
print("c = ", c)



ax =  [1 2 3 4] ; ay =  [5 6 7 8]
ax + ay =  [ 6  8 10 12]
ax * ay =  [ 5 12 21 32]
np.sqrt(ax) =  [1.         1.41421356 1.73205081 2.        ]
a[1] [5 6 7 8]
a[:,1] [ 2  6 10]
c =  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 10 10]]


#### Linear Algebra

In [23]:
import numpy as np
m = np.matrix([[1, -2, 3], [0, 4, 5], [7, 8, -9]])
print("m = ", m)

# return transpose
print("m.T = ", m.T)

# return inverse
print("m.T = ", m.T)

# vector mltiply
v = np.matrix([[2], [3], [4]])
print("v = ", v)
print("m * v = ", m * v)


m =  [[ 1 -2  3]
 [ 0  4  5]
 [ 7  8 -9]]
m.T =  [[ 1  0  7]
 [-2  4  8]
 [ 3  5 -9]]
m.T =  [[ 1  0  7]
 [-2  4  8]
 [ 3  5 -9]]
v =  [[2]
 [3]
 [4]]
m * v =  [[ 8]
 [32]
 [ 2]]
