# NumPy
In this notebook we will study NumPy module. NumPy is high efficient multidimensional array providing vectorized arithmetic operations and sophisticated broadcasting capabilities.

## Numpy arrays
Numpy arrays are used to calculate array and liner algebra

### Initalize array

In [35]:
# Load array from list
import numpy as np
ax = np.array([1,2,3,4,5])
data = list([5,6,7,8,9])
ay = np.array(data)
print("ax = ", ax)
print("ay = ", ay)

ax =  [1 2 3 4 5]
ay =  [5 6 7 8 9]
array =  [[1.  2.  3. ]
 [4.1 5.2 6.3]]
array.ndim =  2
array.shape =  (2, 3)
array.dtype =  float64
array =  [4 5 6]
array =  [[0. 0. 0.]
 [0. 0. 0.]]
array =  [1 2 3 4 5 6 7 8 9]


In [38]:
# 2D np.array
array = np.array([[1,2,3], [4.1, 5.2, 6.3]])
print("array = ", array)
print("array.ndim = ", array.ndim)
print("array.shape = ", array.shape)
print("array.dtype = ", array.dtype)

array =  [[1.  2.  3. ]
 [4.1 5.2 6.3]]
array.ndim =  2
array.shape =  (2, 3)
array.dtype =  float64


In [37]:
# Convert string to float, then to integter
array = np.array(["4.1", "5.2", "6.3"], np.float64)
array = array.astype(np.int32)
print("array int = ", array)

array int =  [4 5 6]


In [73]:
# Initialize np.array with zero
array = np.zeros((2,3))
print("array zeros = ", array)

array zeros =  [[0. 0. 0.]
 [0. 0. 0.]]


In [40]:
# Initialize np.array with range
array = np.arange(1, 10)
print("array = ", array)

array =  [1 2 3 4 5 6 7 8 9]


### Calculate Arrays and Scalars

In [43]:
# calculate matrix
import numpy as np
ax = np.array([1,2,3,4])
ay = np.array([5,6,7,8])
print("ax = ", ax, "; ay = ", ay)
print("ax + ay = ", ax + ay)
print("ax * ay = ", ax * ay)
print("1 / ax = ", 1 / ax)
print("ax ** 0.5 = ", ax ** 0.5)

ax =  [1 2 3 4] ; ay =  [5 6 7 8]
ax + ay =  [ 6  8 10 12]
ax * ay =  [ 5 12 21 32]
np.sqrt(ax) =  [1.         1.41421356 1.73205081 2.        ]
1 / ax =  [1.         0.5        0.33333333 0.25      ]
ax ** 0.5 =  [1.         1.41421356 1.73205081 2.        ]
a[1] [5 6 7 8]
a[:,1] [ 2  6 10]
c =  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 10 10]]


In [137]:
import numpy as np
m = np.matrix([[1, -2, 3], [0, 4, 5], [7, 8, -9]])
print("m = ", m)

# return transpose
print("m.T = ", m.T)

# return inverse
print("m.T = ", m.T)

# vector mltiply
v = np.matrix([[2], [3], [4]])
print("v = ", v)
print("m * v = ", m * v)

m =  [[ 1 -2  3]
 [ 0  4  5]
 [ 7  8 -9]]
m.T =  [[ 1  0  7]
 [-2  4  8]
 [ 3  5 -9]]
m.T =  [[ 1  0  7]
 [-2  4  8]
 [ 3  5 -9]]
v =  [[2]
 [3]
 [4]]
m * v =  [[ 8]
 [32]
 [ 2]]


### Arrays Indexing and Slicing

#### Select a cell

In [56]:
# select rows and columns
import numpy as np
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
# select a cell
print("a[2][2] = ",  a[2][2])
print("a[2, 1]", a[2, 1])


# select row 1 
print("a[1]", a[1])

a[2][2] =  11
a[2, 1] 10
a[1] [5 6 7 8]


#### Select a slice

In [59]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# print a sub slice
print("a[:2, 1:]", a[:2, 1:])
print("a[2]", a[2])
print("a[2, :]", a[2, :])
print("a[2:, :]", a[2:, :])
print("a[:, :2]", a[:, :2])
print("a[1, :2]", a[1, :2])
print("a[1:2, :2]", a[1:2, :2])


# select a slice in row 
print("a[1, 1:3]", a[1, 1:3])
# set a slice in row to a value
a_slice = a[1, 1:3]
a_slice[:] = 88
print("a = ", a)

# The following statement does not assign value to slice.
a_slice = 99
print("a = ", a)

# select col 1 
print("a[:,1]", a[:,1])

# set values greater than 10 to 10
c = np.where(a < 10, a, 10)
print("c = ", c)

a[:2, 1:] [[2 3]
 [5 6]]
a[2] [7 8 9]
a[2, :] [7 8 9]
a[2:, :] [[7 8 9]]
a[:, :2] [[1 2]
 [4 5]
 [7 8]]
a[1, :2] [4 5]
a[1:2, :2] [[4 5]]
a[1, 1:3] [5 6]
a =  [[ 1  2  3]
 [ 4 88 88]
 [ 7  8  9]]
a =  [[ 1  2  3]
 [ 4 88 88]
 [ 7  8  9]]
a[:,1] [ 2 88  8]
c =  [[ 1  2  3]
 [ 4 10 10]
 [ 7  8  9]]


#### Auto fill an array

In [85]:
import numpy as np
# Set value by rows
array = np.empty((8, 4))
for i in range(0, 8) :
    array[i] = i
print("array = ", array)
print("array[[4, 3, 0, 6]] = ", array[[4, 3, 0, 6]])
print("array[[-3, -1]] = ", array[[-3, -1]])

array =  [[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]
array[[4, 3, 0, 6]] =  [[4. 4. 4. 4.]
 [3. 3. 3. 3.]
 [0. 0. 0. 0.]
 [6. 6. 6. 6.]]
array[[-3, -1]] =  [[5. 5. 5. 5.]
 [7. 7. 7. 7.]]


#### Generate 2D array

In [88]:
import numpy as np
# Generate 2D array
array = np.arange(12).reshape(4, 3)
print("array = ", array)

# select a combination of selected rows and columns
arr_selected = array[np.ix_([1, 3, 2], [0, 2])]
print("arr_selected = ", arr_selected)


array =  [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
arr_selected =  [[ 3  5]
 [ 9 11]
 [ 6  8]]


#### Select by condition

In [71]:
import numpy as np
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.arange(1, 8)
print("data = ", data)
print("data[names == 'Bob'] = ", data[names == 'Bob'])
print("data[~(names == 'Bob')] = ", data[~(names == 'Bob')])
print("data[ data > 5] = ", data[ data > 5])



data =  [1 2 3 4 5 6 7]
data[names == 'Bob'] =  [1 4]
data[~(names == 'Bob')] =  [2 3 5 6 7]
data[ data > 5] =  [6 7]


#### Transpose array

In [103]:
import numpy as np
# generate array
array = np.arange(15).reshape((3, 5))
print("array = ", array)

print("array.T = ", array.T)
print("np.transpose(array) = ", np.transpose(array))

a = np.array([1, 2, 3, 4])
print("a =", a)
np.transpose(a)
print("np.transpose(a) =", np.transpose(a))

array =  [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
array.T =  [[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
np.transpose(array) =  [[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
a = [1 2 3 4]
np.transpose(a) = [1 2 3 4]


In [104]:
arr = np.arange(16).reshape(2, 2, 4)
print("arr =", arr)
print("arr.transpose(1,0, 2) = ", arr.transpose(1, 0, 2))

a = np.arange(6).reshape((1, 2, 3))
print("a = ", a)
print("np.transpose(a, (1, 0, 2)) = ", np.transpose(a, (1, 0, 2)))


arr = [[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
arr.transpose(1,0, 2) =  [[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]
a =  [[[0 1 2]
  [3 4 5]]]
np.transpose(a, (1, 0, 2)) =  [[[0 1 2]]

 [[3 4 5]]]


### Array function

#### Unary functions
| Function | Description |
| --- | --- |
| abs | Compute the absolute value element-wise for integer and float or complex values.|
| fabs | Compute fast absolute value without complex value. |
| sqrt | Compute the square root of each element. |
| sqaure | Compute Square of each element. |
| exp | Compute exponent e^x of each element. |
| log, log10, log2 | Compute logarithm (base e, 10, 2). |
| sign | Compute the sign of each element: 1: +, 0: 0, -1: - |
| ceil | Compute the ceiling of each element. smallest integer >= x. |
| floor | Compute the floor of each element. greatest integer <= x. |
| rint | Round elements to the nearest integer. |
| modf | Return fractional and integral parts of array as separate array. |
| isnan | Whether each element is NaN or not. |
| isinf | Whether each element is finite or not. |
| cos, cosh, sin, sinh, tan, tanh | Regular and hyperbolic trigonometric functions. |
| arccos, arccosh, arcsin, arcsinh, arctan, arctanh | Inverse trigonometric functions. |
| logical_not | Compute truth value of not x element-wise. Equivalent to -x |  


#### Binary functions
| Function | Description |
| --- | --- |
| add | Add corresponding elements in array.|
| subtract | Subtract elements in second array from first array. |
| multiply | Multiply array elements. |
| divide, floor_divide | Divide or floor divide (truncating the remainder). |
| power | Raise elements in first array to powers indicated in second array. |
| maximum, fmax | Element-wise maximum. fmax ignores NaN. |
| minimum, fmin | Element-wise minimum. fmin ignores NaN. |
| mod | Element-wise modulus (remainder of division) |
| copysign | Compute sign of values in second argument to values in first argument. |
| greater, greater_equal, less, less_equal, equal, not_equal | Perform element-wise comparison, yielding boolean array. >, >=, <, <=, ==, !=. |
| logical_and, logical_or, logical_xor | Compute element-wise truth value of logical operation. Equivalent to inflix operators &, \|, ^ |


In [109]:
# calculate fractional for random numbers
from numpy.random import randn
import numpy as np
x_arr = randn(8)
y_arr = randn(8)
print("x_arr", x_arr)
print("y_arr", y_arr)
print("np.maximum(x_arr, y_arr) = ", np.maximum(x_arr, y_arr))

x_arr [ 0.31415251 -1.52644964  0.05911827  0.86386507 -2.10193892 -0.25287658
  1.93367805  1.24702356]
y_arr [ 0.12414042 -1.68420596 -0.67228853 -1.54199383 -0.99074767  1.49219249
 -0.74940807 -1.84641181]
np.maximum(x_arr, y_arr) =  [ 0.31415251 -1.52644964  0.05911827  0.86386507 -0.99074767  1.49219249
  1.93367805  1.24702356]


#### Expressing Conditional Logic as Array Operations

In [110]:
import numpy as np
x_arr = np.array([1, 3, 5, 7, 9])
y_arr = np.array([2, 4, 6, 8, 10])
cond = np.array([True, False, True, True, False])
result = np.where(cond, x_arr, y_arr)
print("x_arr = ", x_arr)
print("y_arr = ", y_arr)
print("cond = ", cond)
print("result = ", result)

x_arr =  [1 3 5 7 9]
y_arr =  [ 2  4  6  8 10]
cond =  [ True False  True  True False]
result =  [ 1  4  5  7 10]


#### Mathematical and Statistical Methods

| Method | Description |
| --- | --- |
| sum | Sum of all the elements in the array ot along an axis. Zero-length arrays have sum 0 |
| mean | Arithmetric mean. Zero-length arrays have NaN mean |
| std, var | Standard deviation and variance, respectively, with optional degrees of freedom adjustment (default denominator n) |
| min, max | Minimum and maximum |
| argmin, argmax | Indices of minimum and maximum elements, respectively |
| cumsum | Cumulative sum of elements starting from 0 |
| cumprod | Cumulative product of elements starting from 1 |


In [123]:
import numpy as np
# sum all positive values
array = np.array([1, -2, 3, -4, 5])
print("array = ", array)
print("sum positive numbers in array: ", np.sum(array[array > 0]))
print("count positive numbers in array: ", (array > 0).sum())


array =  [ 1 -2  3 -4  5]
sum positive numbers in array:  9
count positive numbers in array:  3


In [121]:
import numpy as np
array = np.array([[0, 1, 2], [3, 4, 5], [6,7,8]])
print("array = ", array)
print("array.cumsum(0) = ", array.cumsum(0))


array =  [[0 1 2]
 [3 4 5]
 [6 7 8]]
array.cumsum(0) =  [[ 0  1  2]
 [ 3  5  7]
 [ 9 12 15]]


#### Sorting

In [128]:
import numpy as np
# random (8)
array = randn(8)
print("array = ", array)
print("array.sort() = ", np.sort(array))


array =  [-0.07831877  0.07237183 -1.82919913  0.59768969 -0.00700295 -0.03829277
  0.7351326  -2.04956399]
array.sort() =  [-2.04956399 -1.82919913 -0.07831877 -0.03829277 -0.00700295  0.07237183
  0.59768969  0.7351326 ]


#### Boolean Array

In [131]:
import numpy as np
bools = np.array([False, False, True, False])
print("bools = ", bools)
print("bools.any() = ", bools.any())
print("bools.all() = ", bools.all())


bools =  [False False  True False]
bools.any() =  True


#### Unique and Other Set Logic

In [148]:
# unique names
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print("names = ", names)
print("np.unique(names) = ", np.unique(names))

# check values in another array
values = np.array([6, 0, 0, 3, 2, 5, 6])
print("values = ", values)
print("np.in1d(values, [2, 3, 6])", np.in1d(values, [2, 3, 6]))

names =  ['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
np.unique(names) =  ['Bob' 'Joe' 'Will']
values =  [6 0 0 3 2 5 6]
np.in1d(values, [2, 3, 6]) [ True False False  True  True False  True]


### Linear Algebra

#### numpy.linalg functions
| Function | Description |
| --- | --- |
| diag | Return the diagnoal elements of a square matrix as a 1D array, or convert a 1D array into a square matrix with zero on the off-diagonal |
| dot | Matrix multiplication |
| trace | Compute the sum of the diagonal elements |
| det | Compute the matrix determinant |
| eig | Compute the eigenvalues and eigenvectors of a square matrix |
| inv | Compute the inverse of a square matrix |
| pinv | Compute the Moore-Penrose pseudo-inverse inverse of a square matrix |
| qr | Compute the OR decomposition |
| svd | Compute the singular value decomposition (SVD) |
| solve | Solve the linear system Ax = b for x, where A is a square matrix |
| lstsq | Compute the least-squares solution to y = Xb |

In [139]:
import numpy as np
x = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
print("x = ", x)
y = np.array([[6.0, 23.0], [-1.0, 7.0], [8.0, 9.0]])
print("y = ", y)

print("x.dot(y) = ", x.dot(y))
print("np.dot(x, y) = ", np.dot(x, y))

x =  [[1. 2. 3.]
 [4. 5. 6.]]
y =  [[ 6. 23.]
 [-1.  7.]
 [ 8.  9.]]
x.dot(y) =  [[ 28.  64.]
 [ 67. 181.]]
np.dot(x, y) =  [[ 28.  64.]
 [ 67. 181.]]


In [146]:
from numpy.linalg import inv, qr
from numpy.random import randn
x = randn(2, 2)
print("x = ", x)
mat = x.T.dot(x)
print("mat = ", mat)
print("inv(mat) = ", inv(mat))
print("mat.dot(inv(mat)) = ", mat.dot(inv(mat)))

q, r = qr(mat)
print("r = ", r)


x =  [[-2.03053155 -0.7914032 ]
 [ 0.60199104  0.61903602]]
mat =  [[4.48545161 1.97962331]
 [1.97962331 1.00952462]]
inv(mat) =  [[ 1.65695387 -3.24919714]
 [-3.24919714  7.36206553]]
mat.dot(inv(mat)) =  [[ 1.00000000e+00  1.45514978e-15]
 [-7.58319252e-17  1.00000000e+00]]
r =  [[-4.90287513 -2.21869469]
 [ 0.          0.12426696]]


### Random number generation

#### Random function
| Function | Description |
| --- | --- |
| seed | Seed the random number generator |
| permutation | Return a random permutation of a sequence, or return a permutation range |
| shuffle | Randomly permute a sequence in place |
| rand | Draw samples from a uniform distribution |
| randint | Draw random integers from a given low-to-high range |
| randn | Draw samples from a normal distribution with mean 0 and standard deviation 1 |
| binomial | Draw samples from a binomial distribution |
| normal | Draw samples from a normal (Gaussian) distribution |
| beta | Draw samples from a beta distribution |
| chisquare | Draw samples from a chi-square distribution |
| gamma | Draw samples from a gamma distribution |
| uniform | Draw samples from a uniform[0, 1] distribution |
 

In [161]:
# draw random samples
import numpy as np
samples = np.random.normal(size = 10)
print ("normal distribution: ", samples)
samples = np.random.uniform(size = 10)
print ("uniform distribution: ", samples)
samples = np.random.randint(0, 10, size = 10)
print ("randint distribution: ", samples)

# simulate random in multiple ways
samples = np.random.randint(0, 10, size=(2, 5))
print ("2 way distribution: ", samples)


normal distribution:  [ 0.17814289 -1.32051171  0.08526446 -0.65755889  1.13056385 -0.95317881
 -0.71073439 -0.52251288 -0.38566095 -0.87389717]
uniform distribution:  [0.70221657 0.42621046 0.25699654 0.02930941 0.72313448 0.20745598
 0.9274611  0.98497382 0.07428828 0.62339257]
randint distribution:  [3 6 7 7 3 2 0 3 0 7]
2 way distribution:  [[1 2 4 5 2]
 [5 4 6 0 9]]
